# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from ..sandboxespb import sandboxes_pb2 as sandboxespb_dot_sandboxes__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in sandboxespb/sandboxes_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class SandboxesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSandbox = channel.unary_unary(
                '/sandboxespb.Sandboxes/CreateSandbox',
                request_serializer=sandboxespb_dot_sandboxes__pb2.CreateSandboxRequest.SerializeToString,
                response_deserializer=sandboxespb_dot_sandboxes__pb2.CreateSandboxResponse.FromString,
                _registered_method=True)
        self.ListSandboxes = channel.unary_unary(
                '/sandboxespb.Sandboxes/ListSandboxes',
                request_serializer=sandboxespb_dot_sandboxes__pb2.ListSandboxesRequest.SerializeToString,
                response_deserializer=sandboxespb_dot_sandboxes__pb2.ListSandboxesResponse.FromString,
                _registered_method=True)
        self.DeleteSandbox = channel.unary_unary(
                '/sandboxespb.Sandboxes/DeleteSandbox',
                request_serializer=sandboxespb_dot_sandboxes__pb2.DeleteSandboxRequest.SerializeToString,
                response_deserializer=sandboxespb_dot_sandboxes__pb2.DeleteSandboxResponse.FromString,
                _registered_method=True)
        self.ClaudeComputerUse = channel.unary_unary(
                '/sandboxespb.Sandboxes/ClaudeComputerUse',
                request_serializer=sandboxespb_dot_sandboxes__pb2.ClaudeComputerUseRequest.SerializeToString,
                response_deserializer=sandboxespb_dot_sandboxes__pb2.ClaudeComputerUseResponse.FromString,
                _registered_method=True)


class SandboxesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateSandbox(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSandboxes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSandbox(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClaudeComputerUse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SandboxesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSandbox': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSandbox,
                    request_deserializer=sandboxespb_dot_sandboxes__pb2.CreateSandboxRequest.FromString,
                    response_serializer=sandboxespb_dot_sandboxes__pb2.CreateSandboxResponse.SerializeToString,
            ),
            'ListSandboxes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSandboxes,
                    request_deserializer=sandboxespb_dot_sandboxes__pb2.ListSandboxesRequest.FromString,
                    response_serializer=sandboxespb_dot_sandboxes__pb2.ListSandboxesResponse.SerializeToString,
            ),
            'DeleteSandbox': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSandbox,
                    request_deserializer=sandboxespb_dot_sandboxes__pb2.DeleteSandboxRequest.FromString,
                    response_serializer=sandboxespb_dot_sandboxes__pb2.DeleteSandboxResponse.SerializeToString,
            ),
            'ClaudeComputerUse': grpc.unary_unary_rpc_method_handler(
                    servicer.ClaudeComputerUse,
                    request_deserializer=sandboxespb_dot_sandboxes__pb2.ClaudeComputerUseRequest.FromString,
                    response_serializer=sandboxespb_dot_sandboxes__pb2.ClaudeComputerUseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sandboxespb.Sandboxes', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sandboxespb.Sandboxes', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Sandboxes(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateSandbox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandboxespb.Sandboxes/CreateSandbox',
            sandboxespb_dot_sandboxes__pb2.CreateSandboxRequest.SerializeToString,
            sandboxespb_dot_sandboxes__pb2.CreateSandboxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSandboxes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandboxespb.Sandboxes/ListSandboxes',
            sandboxespb_dot_sandboxes__pb2.ListSandboxesRequest.SerializeToString,
            sandboxespb_dot_sandboxes__pb2.ListSandboxesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSandbox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandboxespb.Sandboxes/DeleteSandbox',
            sandboxespb_dot_sandboxes__pb2.DeleteSandboxRequest.SerializeToString,
            sandboxespb_dot_sandboxes__pb2.DeleteSandboxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClaudeComputerUse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandboxespb.Sandboxes/ClaudeComputerUse',
            sandboxespb_dot_sandboxes__pb2.ClaudeComputerUseRequest.SerializeToString,
            sandboxespb_dot_sandboxes__pb2.ClaudeComputerUseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
