# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tunnelpb/tunnel.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15tunnelpb/tunnel.proto\x12\x08tunnelpb\"m\n\rTunnelRequest\x12\x31\n\ninitialise\x18\x01 \x01(\x0b\x32\x1b.tunnelpb.InitialiseRequestH\x00\x12\x1e\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x0e.tunnelpb.DataH\x00\x42\t\n\x07request\",\n\x11InitialiseRequest\x12\x17\n\x0f\x65xec_command_id\x18\x01 \x01(\t\"#\n\x04\x44\x61ta\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\r\n\x05\x63lose\x18\x02 \x01(\x08\x32?\n\x06Tunnel\x12\x35\n\x06Tunnel\x12\x17.tunnelpb.TunnelRequest\x1a\x0e.tunnelpb.Data(\x01\x30\x01\x42\x30Z.github.com/clusterfudgeai/fudge/proto/tunnelpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tunnelpb.tunnel_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z.github.com/clusterfudgeai/fudge/proto/tunnelpb'
  _globals['_TUNNELREQUEST']._serialized_start=35
  _globals['_TUNNELREQUEST']._serialized_end=144
  _globals['_INITIALISEREQUEST']._serialized_start=146
  _globals['_INITIALISEREQUEST']._serialized_end=190
  _globals['_DATA']._serialized_start=192
  _globals['_DATA']._serialized_end=227
  _globals['_TUNNEL']._serialized_start=229
  _globals['_TUNNEL']._serialized_end=292
# @@protoc_insertion_point(module_scope)
