# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: logs/logs.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0flogs/logs.proto\x12\x10\x63lusterfudge.log\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd0\x01\n\x0fListLogsRequest\x12\x11\n\thostnames\x18\x01 \x03(\t\x12.\n\nstart_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\x08\x65nd_time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\r\n\x05limit\x18\x04 \x01(\x05\x12\x0f\n\x07sources\x18\x05 \x03(\t\x12\x12\n\nlaunch_ids\x18\x06 \x03(\t\x12\x18\n\x10\x65xec_command_ids\x18\x07 \x03(\t\"7\n\x10ListLogsResponse\x12#\n\x04logs\x18\x01 \x03(\x0b\x32\x15.clusterfudge.log.Log\"\x17\n\x15ListLogSourcesRequest\")\n\x16ListLogSourcesResponse\x12\x0f\n\x07sources\x18\x01 \x03(\t\"\xd4\x01\n\x03Log\x12\x10\n\x08hostname\x18\x01 \x01(\t\x12\x0e\n\x06source\x18\x02 \x01(\t\x12\x10\n\x08\x63ontents\x18\x03 \x01(\t\x12-\n\tlogged_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12+\n\x07seen_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x11\n\ttenant_id\x18\x06 \x01(\t\x12\x11\n\tlaunch_id\x18\x07 \x01(\t\x12\x17\n\x0f\x65xec_command_id\x18\x08 \x01(\t2\xc2\x01\n\x04Logs\x12S\n\x08ListLogs\x12!.clusterfudge.log.ListLogsRequest\x1a\".clusterfudge.log.ListLogsResponse\"\x00\x12\x65\n\x0eListLogSources\x12\'.clusterfudge.log.ListLogSourcesRequest\x1a(.clusterfudge.log.ListLogSourcesResponse\"\x00\x42,Z*github.com/clusterfudgeai/fudge/proto/logsb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'logs.logs_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z*github.com/clusterfudgeai/fudge/proto/logs'
  _LISTLOGSREQUEST._serialized_start=71
  _LISTLOGSREQUEST._serialized_end=279
  _LISTLOGSRESPONSE._serialized_start=281
  _LISTLOGSRESPONSE._serialized_end=336
  _LISTLOGSOURCESREQUEST._serialized_start=338
  _LISTLOGSOURCESREQUEST._serialized_end=361
  _LISTLOGSOURCESRESPONSE._serialized_start=363
  _LISTLOGSOURCESRESPONSE._serialized_end=404
  _LOG._serialized_start=407
  _LOG._serialized_end=619
  _LOGS._serialized_start=622
  _LOGS._serialized_end=816
# @@protoc_insertion_point(module_scope)
