# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: logs/logs.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0flogs/logs.proto\x12\x10\x63lusterfudge.log\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd4\x01\n\x03Log\x12\x10\n\x08hostname\x18\x01 \x01(\t\x12\x0e\n\x06source\x18\x02 \x01(\t\x12\x10\n\x08\x63ontents\x18\x03 \x01(\t\x12-\n\tlogged_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12+\n\x07seen_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x11\n\ttenant_id\x18\x06 \x01(\t\x12\x11\n\tlaunch_id\x18\x07 \x01(\t\x12\x17\n\x0f\x65xec_command_id\x18\x08 \x01(\t2\x06\n\x04LogsB,Z*github.com/clusterfudgeai/fudge/proto/logsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'logs.logs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z*github.com/clusterfudgeai/fudge/proto/logs'
  _globals['_LOG']._serialized_start=71
  _globals['_LOG']._serialized_end=283
  _globals['_LOGS']._serialized_start=285
  _globals['_LOGS']._serialized_end=291
# @@protoc_insertion_point(module_scope)
