# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: resources/resources.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19resources/resources.proto\x12\x0c\x63lusterfudge\"l\n\tResources\x12\x0c\n\x04\x63pus\x18\x01 \x01(\x05\x12\x11\n\tmemory_mb\x18\x02 \x01(\x05\x12\x15\n\rgpu_a100_40gb\x18\x03 \x01(\x05\x12\x15\n\rgpu_a100_80gb\x18\x04 \x01(\x05\x12\x10\n\x08gpu_h100\x18\x05 \x01(\x05\x42\x31Z/github.com/clusterfudgeai/fudge/proto/resourcesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'resources.resources_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z/github.com/clusterfudgeai/fudge/proto/resources'
  _globals['_RESOURCES']._serialized_start=43
  _globals['_RESOURCES']._serialized_end=151
# @@protoc_insertion_point(module_scope)
