# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: resources/resources.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19resources/resources.proto\x12\x0c\x63lusterfudge\"\x91\x01\n\tResources\x12\x0c\n\x04\x63pus\x18\x01 \x01(\x05\x12\x11\n\tmemory_mb\x18\x02 \x01(\x05\x12\x15\n\rgpu_a100_40gb\x18\x03 \x01(\x05\x12\x15\n\rgpu_a100_80gb\x18\x04 \x01(\x05\x12\x10\n\x08gpu_h100\x18\x05 \x01(\x05\x12\x13\n\x0bgpu_rtx3090\x18\x06 \x01(\x05\x12\x0e\n\x06gpu_t4\x18\x07 \x01(\x05\x42\x31Z/github.com/clusterfudgeai/fudge/proto/resourcesb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'resources.resources_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z/github.com/clusterfudgeai/fudge/proto/resources'
  _RESOURCES._serialized_start=44
  _RESOURCES._serialized_end=189
# @@protoc_insertion_point(module_scope)
